Query was executed successfully

Query was executed successfully

Some of stuff...
{i} v_sum
{0} 2800

[An error expected at this place for the query "append(STUFF, TWO_D)". And it failed with error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_MULTIDIMENSIONAL_ARRAY_NOT_ALLOWED. Expected error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_MULTIDIMENSIONAL_ARRAY_NOT_ALLOWED.]

[Query was executed successfully, ignoring data output by this query.]

{i} v_sum
{0} 2800

[An error expected at this place for the query "append(STUFF, TWO_D, x)". And it failed with error code = scidb::SCIDB_SE_EXECUTION::SCIDB_LE_CHUNK_OUT_OF_BOUNDARIES. Expected error code = scidb::SCIDB_SE_EXECUTION::SCIDB_LE_CHUNK_OUT_OF_BOUNDARIES.]

[An error expected at this place for the query "append(build(STUFF, random()), IDONTEXIST)". And it failed with error code = scidb::SCIDB_SE_QPROC::SCIDB_LE_ARRAY_DOESNT_EXIST. Expected error code = scidb::SCIDB_SE_QPROC::SCIDB_LE_ARRAY_DOESNT_EXIST.]

[An error expected at this place for the query "append(flatten(build(STUFF, random())), IDONTEXIST)". And it failed with error code = scidb::SCIDB_SE_QPROC::SCIDB_LE_ARRAY_DOESNT_EXIST. Expected error code = scidb::SCIDB_SE_QPROC::SCIDB_LE_ARRAY_DOESNT_EXIST.]

Query was executed successfully

Query was executed successfully

